### PR TITLE
6 get an access token from an access identity provider

### PR DESCRIPTION
**Pull request by raghunandanarava**

### CODE REVIEW

**Comment by prebbe** [comment]
The input for the new functionality is provided via an .env-file. Should we add the option to pass these information directly to the function via the frontend or the endpoint?

**Comment by prebbe** [comment]
I currently cannot create a request to get a token from the identity-provider. Can you provide a small documentation how to use/test this function?

**Comment by raghunandanarava** [comment]
There are two methods implemented for the same function. I can give you the general cURL commands for your keycloak's instance where you replace with the required information for testing this.

### GET Request
- First setup your local identity provider instance's CLIENT_ID, CLIENT_SECRET, and AUDIENCE in the .env file.
- Then start the application in dev mode.
- Use this cURL command for getting a response by replacing the ISSUER_STRING with your local instance's to get a token: curl --request GET --url 127.0.0.1:8081/api/token?issuer=$ISSUER_STRING --header 'content-type: application/json'
- An 400 BAD REQUEST exception is raised when provided with an ISSUER_STRING which is not available or incorrect with an error message "invalid issuer"

### POST Request
- Use this cURL command for getting an access token by replacing the issuer's client credentials information: curl --request POST --url 127.0.0.1:8081/api/token?issuer=$ISSUER_STRING --header 'content-type: application/json' --data '{"client_id":$CLIENT_ID,"client_secret":$CLIENT_SECRET,"audience":$AUDIENCE,"grant_type":"client_credentials"}'
- If any of the information provided in the request is incorrect, the corresponding error message is returned with a corresponding exception raised, i.e., if the ISSUER_STRING is unavailable/incorrect, then a 400 BAD REQUEST exception is raised with an error message "invalid_issuer." The other case where either of the strings in the data json is wrong, then a 401 UNAUTHORIZED exception is raised with an error message "Access denied".

Please, let me know if you need more details on this part.

**Comment by prebbe** [comment]
I currently get a 415-Errorcode (Invalid Media-Type) for the token-request, if I try to test this functionality against a local keycloak-instance.

**Comment by prebbe** [comment]
When I run the latest commit, it throws an error during the request to the token endpoint, because the qs reference is undefined.

**Comment by raghunandanarava** [comment]
> because the qs reference is undefined.

I have made a change now, can you please check if this is working now?
Unfortunately, my keycloak local instance isn't working as expected because docker not working on my laptop due to a virtualisation problem, thenceforth I am unable to check against it. Please, let me know if this is working now. @prebbe

**Comment by prebbe** [comment]
Now it works.

**Pull request merged**
