### PR TITLE
34 get the public key from a file or the identity provider

### PR DESCRIPTION
**Pull request by prebbe**

### CODE REVIEW

**Comment by prebbe** [comment]
How to test:
1. Create a pem-file from the key-material of your identity-provider. (For example: Copy the key-material from your local keycloak-instance to a pem-file (don't forget the header!).
2. Start the application and go to {{http://localhost:8081/api/token/decode}}
3. Input the information for the issuer and the token
4. Untick the checkbox, so the application knows to use the keymaterial specified below
5. Input the algorithm to use for decoding (for a standard keycloak instance this should be RS256) and the path to the created pem-file.
6. Click submit.

**Comment by raghunandanarava** [comment]
Can you provide me with an example .pem file that you have used? I tried with mine, maybe the format isn't correct.

**Comment by raghunandanarava** [comment]
This is working as expected for the acceptance criteria. But I have a few questions.

1. The dropdown with the algorithms is for future functionality, right?
2. I did a test by selecting the wrong algorithm, for example, EdDSA instead of RS256 (actually any). It seems that it produces an output with the decoded token. Should this be worked on or will this be fixed in future implementations maybe?

**Comment by prebbe** [comment]
The dropdown represents the different algorithms that are supported for the verification of the signed tokens (see [documentation](https://github.com/panva/jose/issues/210)). But it seems I misunderstood the way this key is used in the verification. Let me have another look at this.

**Comment by prebbe** [comment]
Since the verification does not automatically check the algorithm specified in the key against the algorithm in the token, I now pass this information via the options object. This should ensure that the token is only validated against the key-material if the specified algorithm matches an allowed algorithm in the token.

**Pull request merged**
